# Generated by Django 4.0.2 on 2022-03-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.BinaryField(editable=True, max_length=1048576),
        ),
    ]
