# Generated by Django 4.0.2 on 2022-03-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_message_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='picture',
        ),
    ]
