# Generated by Django 4.0.2 on 2022-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_picture_message_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='is_tetatet',
            field=models.BooleanField(default=False),
        ),
    ]
