# Generated by Django 4.0.2 on 2022-04-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_dialogue_is_tetatet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureV2',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('data', models.BinaryField(max_length=1048576)),
                ('sha256', models.CharField(max_length=64)),
            ],
        ),
    ]
