# Generated by Django 4.0.2 on 2022-04-21 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_picturev2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='picture',
        ),
        migrations.AddField(
            model_name='message',
            name='picture_id',
            field=models.UUIDField(default=uuid.uuid1()),
            preserve_default=False,
        ),
    ]
