# Generated by Django 4.0.2 on 2022-04-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_remove_message_picture_id_message_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
